## Practical 3


In this class, you will be asked to solve 2 exercises about NumPy.

Good work!

### Exercise 1

#### 1. Import the numpy package under the name np¶

In [1]:
#1
import numpy as np

#### 2. Create a null vector of size 10 

In [33]:
#2
z=np.zeros(10)
z.size

10

#### 3.  Create a null vector of size 10 but the fifth value which is 1 

In [35]:
#3
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49

In [39]:
#4
u=np.arange(10,50)
u

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 10x10 array with random values and find the minimum and maximum values

In [83]:
#5 
i=np.random.randn(10,10)
#print(i)
print(i.max()) # i.max() == np.max(i)
print(i.min()) # i.min() == np.min(i)

3.1754349613664856
-1.8768646839571557


#### 6. Create a random vector of size 30 and find the mean value

In [85]:
#6
o=np.random.randn(30)
o.mean()

-0.20928618150051062

#### 7. Rescale a 5x5 random matrix, with a normalization and strandartization

In [94]:
#7
p = np.random.randn(25)
p.reshape(5,5)
p = (p-p.min()/(p.max()-p.min()))
print(p)

a=np.random.randn(5,5)
a=((a-a.mean())/a.std())
print(a)


[-0.92027449  0.1914875  -0.59047552 -1.41115929  2.0953886   2.56253118
  0.01943997  0.93217779 -1.11255659 -1.6871565  -0.12119194  1.26696534
  1.44634635  0.78993682  1.99205281  0.87740484  1.60016368  0.14403461
  0.19240828  0.70959974 -1.1901828   0.86320466  0.22260358 -0.99829262
 -1.42545588]
[[ 0.08513753  0.28928145  0.09892168 -1.72480645  0.1180485 ]
 [-0.73770931 -0.40925642  0.31611215 -1.40432888 -0.91249895]
 [ 3.07426536 -0.01365225  1.11859337  0.40663713  0.18950605]
 [-1.63079602 -0.62509158  0.24778797  0.78429686  0.71788481]
 [-0.94013622 -0.60498559  1.35303682 -0.05094371  0.25469569]]


#### 8. Create a random vector of size 10 and sort it

In [98]:
#8
s = np.random.randn(10)
s.sort()
s

array([-2.11483094, -1.73601494, -1.44219172, -1.17960312, -1.07265115,
       -0.35272707,  0.34058242,  1.21395024,  1.736728  ,  1.89999289])

#### 9. Create random vector of size 10 and replace the maximum value by 0 

In [102]:
#9
s[s.argmax()] = 0
s

array([-2.11483094, -1.73601494, -1.44219172, -1.17960312, -1.07265115,
       -0.35272707,  0.34058242,  1.21395024,  0.        ,  0.        ])

#### 10. Create a vector with values ranging from 0 to 9. Replace all odd numbers in the array with -1


In [108]:
#10
d=np.arange(0,10)
d[d%2==1] = -1
print(d)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 11. Multiply a 5x3 matrix (ones) by a 3x2 matrix (ones) - real matrix product 

In [112]:
#11
f=np.dot(np.ones(5,3)), np.ones(3,2)
print(f)

### Exercise 2

We have been able to collect data for 4 flats below: Their `surface` (square feet), `bedrooms` and `floors` numbers are the 3 **features** of our problem, and the `price` (in thousands of $) is our **target**:

|flats |surface|bedrooms|floors|price|
|------|-------------|--------|------|------------|
|flat1 |620|1|1|244|
|flat2 |3280|4|2|671|
|flat3 |1900|2|2|504|
|flat4 |1320|3|3|510|

A first approach is to try to find a **linear** relation between the `price` and the 3 features, by solving this system of equations:

$$\begin{cases}
    244 = \theta_0 + 620\theta_1 + 1\theta_2 + 1\theta_3 \\
    671 = \theta_0 + 3280\theta_1 + 4\theta_2 + 2\theta_3 \\
    504 = \theta_0 + 1900\theta_1 + 2\theta_2 + 2\theta_3 \\
    510 = \theta_0 + 1320\theta_1 + 3\theta_2 + 3\theta_3
\end{cases}$$

Which can be translated into a matricial equation:

$$Y = X\theta$$

$$\begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix} = \begin{bmatrix}
    1 & 620 & 1 & 1 \\
    1 & 3280 & 4 & 2 \\
    1 & 1900 & 2 & 2 \\
    1 & 1320 & 3 & 3
\end{bmatrix} \begin{bmatrix}
    \theta_1 \\
    \theta_2 \\
    \theta_3 \\
    \theta_4
\end{bmatrix}$$

where $Y$ is the vector of `Price`, $X$ is the matrix of features and $\theta$ (theta) is the vector of coefficients to be found.

If $\theta$ is found, the price of any new flat could be estimated using $$Y_{flat5} = X_{flat5}\theta$$

### 1 Define the matrix `X` of features

#### a) 

Create a (4,3) `numpy.ndarray` storing the values of the 3 features (surface, bedrooms, floors) for the 4 observations. Double check its `shape`, `size` and `dim`

In [130]:
#a
arr = np.array([(620,1,1), (3280,4,2), (1900,2,2), (1320,3,3)], dtype=int)
arr

array([[ 620,    1,    1],
       [3280,    4,    2],
       [1900,    2,    2],
       [1320,    3,    3]])

#### b)

Create a "constant" vector of 1's, checking its shape.

In [12]:
#b

### c)

Use `numpy.hstack` to create the (4,4) matrix X by concatenating the vector in b) with the matrix in a)

In [13]:
#c

### 2 Define the vector `Y` of Prices

$Y = \begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix}$

In order to match our matricial representation $Y = X\theta$, what should be the shape of $Y$ ? Define $Y$ below

Hint:

Y should be a (4,1) array, equivalent to a flat "vector", represented vertically
</details>

In [15]:
#2

### 3 Find the solution of the system

Now is the time to find the vector of coefficients $\theta$ !

The solution of the equation is:
 
$$ X\theta = Y \\
\Leftrightarrow X^{-1}X\theta = X^{-1}Y \\
\Leftrightarrow \theta = X^{-1}Y$$

where $X^{-1}$ is the inverse of $X$.

### a)

Compute the inverse of the matrix X using the correct Numpy method.

In [16]:
#a

You can check if the inversion worked by testing:

$$X^{-1}X = I_4$$
where $I_4$ is the 4 by 4 identity matrix.

### b)

Define I4 using the correct Numpy method.

In [17]:
#b

### c)

Now compute $X^{-1}X$.

In [18]:
#c

Does it look like $I_4$?


#### d)

Compute $\theta$ (remembering that $\theta = X^{-1}Y$).

In [19]:
#d

### 4. Estimation of a new flat price

You finally solved the system finding $\theta$, you are able to estimate the `Price` (in thousands of $) of a 5th flat given these characteristics:

- `Surface`: 3000 $ft^2$
- `Bedrooms`: 5 
- `Floors`: 1

with the following formula:

$$Y_{flat5} = X_{flat5}\theta$$

Create X5 from the information above (not forgetting the constant) and use the formula above and our previous vector $\theta$ to estimate the price (Y5) of this new flat. Print it to the screen.

In [20]:
#4